import mongoose from 'mongoose';

const userSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true },
  phone: { type: String, required: true },
  language: { type: String, required: true },
  category: { type: String, required: true },
  availability: { type: String },
  qualification: { type: String, required: true },
  address: { type: String, required: true },
  panNumber: { type: String, required: true },
  aadharNumber: { type: String, required: true },
  gender: { type: String, required: true },
  religion: { type: String, required: true },
  city: { type: String, required: true },
  state: { type: String, required: true },
  pinCode: { type: String, required: true },
  maritalStatus: { type: String, required: true },
  wifeName: { type: String },
  wifeAadharNumber: { type: String },
  wifePanNumber: { type: String },
  jobStatus: { type: String, required: true },
  bankName: { type: String, required: true },
  accountNumber: { type: String, required: true },
  branch: { type: String, required: true },
  ifscCode: { type: String, required: true },
  paymentReceiver: { type: String, required: true },
  relationBankName: { type: String },
  relationAccountNumber: { type: String },
  relationBranch: { type: String },
  relationIfscCode: { type: String },
  guardianOptions: [{ type: String }],
  customRequirements: { type: String },
  marksheet: { type: String },
  image: { type: String },
  checkBook: { type: String },
});

export default mongoose.model('User', userSchema);
